name: looks_like_it
description: "A Flutter application for comparing images using various image hashing algorithms. Features include folder comparison, similarity threshold adjustment, and a visual difference display."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.1.0+13

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  before_after: ^3.0.0+1
  crypto: ^3.0.5
  cupertino_icons: ^1.0.6
  file_picker: ^8.0.5
  fluentui_system_icons: ^1.1.244
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_svg: ^2.0.10+1
  hooks_riverpod: ^2.5.1
  image: ^4.2.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  layout: ^1.0.5
  logger: ^2.4.0
  path: ^1.9.0
  path_provider: ^2.1.3
  photo_view: ^0.15.0
  riverpod_annotation: ^2.3.5
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0
  url_launcher: ^6.3.1
  window_manager: ^0.3.9

dev_dependencies:
  build_runner: ^2.4.11
  custom_lint: ^0.6.4
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1
  msix: ^3.16.8
  riverpod_generator: ^2.4.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/icons/
    - assets/images/

flutter_launcher_icons:
  android: false
  ios: false
  image_path: "assets/icons/icon.png"
  windows:
    generate: true
    icon_size: 48

msix_config:
  display_name: Looks Like It
  logo_path: "assets/icons/icon.png"